[package]
name = "aion_config"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
aion_common = { workspace = true }
serde = { workspace = true }
toml = { workspace = true }
thiserror = { workspace = true }
