[package]
name = "aion_diagnostics"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
aion_common = { workspace = true }
aion_source = { workspace = true }
serde = { workspace = true }

[dev-dependencies]
serde_json = "1"
