[package]
name = "aion_lint"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
aion_common = { workspace = true }
aion_ir = { workspace = true }
aion_diagnostics = { workspace = true }
