[package]
name = "aion_common"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
serde = { workspace = true }
thiserror = { workspace = true }
lasso = { workspace = true }
xxhash-rust = { workspace = true }

[dev-dependencies]
serde_json = "1"
