[package]
name = "aion_verilog_parser"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
aion_common = { workspace = true }
aion_source = { workspace = true }
aion_diagnostics = { workspace = true }
